import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Terms of Service',
    description: 'AIPress terms of service — rules and conditions for using our platform.',
};

export default function TermsPage() {
    return (
        <div className="container-custom" style={{ padding: '60px 24px', maxWidth: '800px', margin: '0 auto' }}>
            <h1 style={{ fontSize: '2rem', fontWeight: 700, marginBottom: '32px', color: 'var(--neon-orange)' }}>
                Terms of Service
            </h1>
            <div style={{ color: 'var(--text-muted)', lineHeight: 1.8, fontSize: '0.95rem' }}>
                <p style={{ marginBottom: '20px' }}>
                    <strong style={{ color: 'var(--text-main)' }}>Last updated:</strong> February 2026
                </p>

                <h2 style={{ fontSize: '1.25rem', color: 'var(--text-main)', margin: '32px 0 12px' }}>1. Acceptance</h2>
                <p style={{ marginBottom: '16px' }}>
                    By accessing AIPress, you agree to these Terms of Service. If you do not agree,
                    please do not use the platform.
                </p>

                <h2 style={{ fontSize: '1.25rem', color: 'var(--text-main)', margin: '32px 0 12px' }}>2. Content</h2>
                <p style={{ marginBottom: '16px' }}>
                    All content on AIPress is provided for informational purposes only.
                    AIPress uses AI-assisted content generation. While we strive for accuracy,
                    we do not guarantee the completeness or accuracy of any content.
                </p>

                <h2 style={{ fontSize: '1.25rem', color: 'var(--text-main)', margin: '32px 0 12px' }}>3. Intellectual Property</h2>
                <p style={{ marginBottom: '16px' }}>
                    All original content, design, and branding on AIPress are the intellectual
                    property of AIPress. Unauthorized reproduction is prohibited.
                </p>

                <h2 style={{ fontSize: '1.25rem', color: 'var(--text-main)', margin: '32px 0 12px' }}>4. AI Search</h2>
                <p style={{ marginBottom: '16px' }}>
                    The AI-powered search feature is rate-limited and provided as-is.
                    Results are generated by AI and may not always be accurate.
                </p>

                <h2 style={{ fontSize: '1.25rem', color: 'var(--text-main)', margin: '32px 0 12px' }}>5. Limitation of Liability</h2>
                <p style={{ marginBottom: '16px' }}>
                    AIPress shall not be liable for any damages arising from the use of this platform
                    or reliance on its content.
                </p>

                <h2 style={{ fontSize: '1.25rem', color: 'var(--text-main)', margin: '32px 0 12px' }}>6. Contact</h2>
                <p style={{ marginBottom: '16px' }}>
                    For questions about these terms, contact us at{' '}
                    <a href="mailto:contact@aipress.business" style={{ color: 'var(--neon-orange)' }}>
                        contact@aipress.business
                    </a>.
                </p>
            </div>
        </div>
    );
}
